/*
Exo 1
*/
1. select * from user_tables  ;
2. select * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ABONNE' ;
3. select CONSTRAINT_NAME from user_constraints WHERE CONSTRAINT_NAME LIKE 'PK_%';
3. select CONSTRAINT_NAME from user_constraints WHERE CONSTRAINT_NAME LIKE 'FK_%';
4. select * from user_constraints WHERE CONSTRAINT_NAME LIKE 'PK_%';
5. SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME='ABONNE';

/*
Exo 2
*/
GRANT select on ABONNE to e20190007140;

SELECT * FROM USER_TAB_PRIVS_MADE;
SELECT * FROM USER_TAB_PRIVS_MADE;
REVOKE SELECT,UPDATE,INSERT ON LIVRE FROM e20190007140;
